/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/BottomNavigation`; params?: Router.UnknownInputParams; } | { pathname: `/components/GoogleMapComponent`; params?: Router.UnknownInputParams; } | { pathname: `/components/RestaurantList`; params?: Router.UnknownInputParams; } | { pathname: `/components/SafePlatesHeader`; params?: Router.UnknownInputParams; } | { pathname: `/components/SearchBar`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/components/BottomNavigation`; params?: Router.UnknownOutputParams; } | { pathname: `/components/GoogleMapComponent`; params?: Router.UnknownOutputParams; } | { pathname: `/components/RestaurantList`; params?: Router.UnknownOutputParams; } | { pathname: `/components/SafePlatesHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/components/SearchBar`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/components/BottomNavigation${`?${string}` | `#${string}` | ''}` | `/components/GoogleMapComponent${`?${string}` | `#${string}` | ''}` | `/components/RestaurantList${`?${string}` | `#${string}` | ''}` | `/components/SafePlatesHeader${`?${string}` | `#${string}` | ''}` | `/components/SearchBar${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/BottomNavigation`; params?: Router.UnknownInputParams; } | { pathname: `/components/GoogleMapComponent`; params?: Router.UnknownInputParams; } | { pathname: `/components/RestaurantList`; params?: Router.UnknownInputParams; } | { pathname: `/components/SafePlatesHeader`; params?: Router.UnknownInputParams; } | { pathname: `/components/SearchBar`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
